# Generated by Django 2.2 on 2020-10-07 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250, verbose_name='Descripción de la mascota')),
                ('serie', models.CharField(max_length=25, verbose_name='Número de Serie')),
                ('stock', models.PositiveIntegerField(help_text='Solo ingresar números enteros positivos', verbose_name='Cantidad de existencias')),
                ('cost', models.PositiveIntegerField(help_text='Solo ingresar números enteros positivos', verbose_name='Costo de la mascota')),
                ('price', models.PositiveIntegerField(help_text='Solo ingresar números enteros positivos', verbose_name='Precio de Venta de la mascota')),
                ('state', models.BooleanField(default='True', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Ejemplo: Caninos, Felinos, Reptiles, etc.', max_length=50, verbose_name='Especie de Mascotas')),
            ],
            options={
                'verbose_name': 'Especie de mascota',
                'verbose_name_plural': 'Especies de mascotas',
                'db_table': 'productbrand',
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de recibido')),
                ('detail', models.TextField(max_length=250, verbose_name='Detalle o Motivo')),
                ('state', models.BooleanField(default=False, verbose_name='Cubre garantia')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Client', verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.Product', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
                'db_table': 'warranty',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Ejemplo: Mamifero, Reptil, Ave,etc.', max_length=50, verbose_name='Tipo de Mascota')),
            ],
            options={
                'verbose_name': 'Tipo de mascota',
                'verbose_name_plural': 'Tipos de mascotas',
                'db_table': 'producttype',
                'unique_together': {('type',)},
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Ejemplo: Labrador, Pastor Aleman, Buldog, etc.', max_length=50, verbose_name='Raza de la mascota')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.ProductBrand', verbose_name='Especie de mascota')),
            ],
            options={
                'verbose_name': 'Raza de la mascota',
                'verbose_name_plural': 'Razas de las mascotas',
                'db_table': 'productmodel',
                'unique_together': {('model',)},
            },
        ),
        migrations.AddField(
            model_name='productbrand',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.ProductType', verbose_name='Tipo de Mascota'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.ProductModel', verbose_name='Nombre de la mascota'),
        ),
        migrations.CreateModel(
            name='ApproveWarranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(verbose_name='Estado')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.Warranty', verbose_name='Garantía')),
            ],
            options={
                'verbose_name': 'Aprobar garantía',
                'verbose_name_plural': 'Aprobar garantías',
                'db_table': 'approvewarranty',
            },
        ),
        migrations.CreateModel(
            name='AddStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('cost', models.PositiveIntegerField(help_text='Solo ingresar números enteros positivos', verbose_name='Costo de la Mascota')),
                ('price', models.PositiveIntegerField(help_text='Solo ingresar números enteros positivos', verbose_name='Precio de Venta de la Mascota')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.Product', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Agregar existencia',
                'verbose_name_plural': 'Agregar existencias',
                'db_table': 'addstock',
            },
        ),
        migrations.AlterUniqueTogether(
            name='productbrand',
            unique_together={('brand',)},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
    ]
