# Generated by Django 2.2 on 2020-10-07 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Mascotas', '0001_initial'),
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='total')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Client', verbose_name='Cliente')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='Saledetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.Product', verbose_name='Mascota')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.Sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de la venta',
                'verbose_name_plural': 'Detalle de las ventas',
                'db_table': 'saledetail',
            },
        ),
    ]
