# Generated by Django 2.2 on 2020-10-07 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Género')),
                ('dateofbirth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('cui', models.CharField(max_length=17, verbose_name='CUI')),
                ('code', models.CharField(help_text='Ejemplo: EMP01', max_length=5, verbose_name='Código de empleado')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección de Residencia')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Municipality', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Ingrese el tipo de número telefonico ya sea Celular, Residencial, Laboral, etc.', max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de número de teléfono',
                'verbose_name_plural': 'Tipos de números de teléfonos',
                'db_table': 'phonetypeemployee',
                'unique_together': {('type',)},
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Solo ingresar números', verbose_name='Número de Teléfono')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.Employee', verbose_name='Cliente')),
                ('phonetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.PhoneType', verbose_name='Tipo de número telefónico')),
            ],
            options={
                'verbose_name': 'Número de teléfono',
                'verbose_name_plural': 'Números de teléfono',
                'db_table': 'phonenumberemployee',
                'unique_together': {('number',)},
            },
        ),
    ]
