# Generated by Django 2.2 on 2020-10-07 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ejemplo: Chiquimula, Jutiapa, Zacapa, etc.', max_length=50, verbose_name='Nombre del Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'department',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Ingrese el tipo de número telefonico ya sea Celular, Residencial, Laboral, etc.', max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de número de teléfono',
                'verbose_name_plural': 'Tipos de números de teléfonos',
                'db_table': 'phonetype',
                'unique_together': {('type',)},
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ejemplo: Chiquimula, Esquipulas, Quezaltepeque, etc.', max_length=50, verbose_name='Nombre del Municipio')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipality',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Género')),
                ('dateofbirth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('cui', models.CharField(max_length=17, verbose_name='CUI')),
                ('nit', models.CharField(help_text='Ejemplo: 1234567-8', max_length=100, verbose_name='NIT')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección de Residencia')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Municipality', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Solo ingresar números', verbose_name='Número de Teléfono')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Client', verbose_name='Cliente')),
                ('phonetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.PhoneType', verbose_name='Tipo de número telefónico')),
            ],
            options={
                'verbose_name': 'Número de teléfono',
                'verbose_name_plural': 'Números de teléfono',
                'db_table': 'phonenumber',
                'unique_together': {('number',)},
            },
        ),
    ]
